import project1 from '../../src/assets/project1.webp';
import project2 from '../../src/assets/project2.webp';
import project3 from '../../src/assets/project3.webp';
import project4 from '../../src/assets/project4.webp';
import project5 from '../../src/assets/project5.webp';
import project6 from '../../src/assets/project6.webp';

/**
 * Access levels
 *  proprietary  → shipped commercial product, source stays closed
 *  open-source  → public repository, source is linkable
 */
export const ACCESS = {
	PROPRIETARY: 'proprietary',
	OPEN_SOURCE: 'open-source',
};

export const projectsData = [
	/* ───────────────────────── AI & Agent Platforms ───────────────────────── */
	{
		id: 1,
		title: 'Satryx Forge™',
		tagline: 'Industrial Operating Intelligence for oil & gas',
		category: 'AI & Agents',
		access: ACCESS.PROPRIETARY,
		year: '2026',
		role: 'Architect & Lead Engineer',
		summary:
			'A vendor-neutral intelligence layer that sits above SAP, Maximo, AVEVA, PI System and Primavera — connecting them, surfacing hidden relationships and preserving engineering knowledge. Every answer it gives is cited with source, assumptions, confidence, rule, calculation and reviewer.',
		highlights: [
			'Industrial Knowledge Graph giving one asset a single identity across every source system',
			'26 A–Z operating modules over six shared intelligence layers',
			'Next.js intelligence plane paired with a real Python deterministic compute plane',
			'Governance, audit trail and role workspaces built in from day one',
		],
		stack: ['Next.js', 'TypeScript', 'Python', 'Knowledge Graph', 'Docker', 'LLM Reasoning'],
		image: null,
		demoUrl: null,
		sourceUrl: null,
		status: 'completed',
	},
	{
		id: 2,
		title: 'MirrorMingo',
		tagline: 'Multilingual AI tutor for African learners',
		category: 'AI & Agents',
		access: ACCESS.PROPRIETARY,
		year: '2026',
		role: 'Lead Engineer',
		metric: '1,589 commits',
		summary:
			'A standalone AI learning platform for K-12 schools, independent learners and undergraduate programmes. Built for OpenAI Build Week and submitted to the Devpost OpenAI hackathon as a multilingual AI tutor for Nigerian learners.',
		highlights: [
			'Tutors in Nigerian Pidgin, Yoruba, Igbo, Hausa and Nigerian English',
			'Offline-first architecture — PostgreSQL in cloud, SQLite lesson packs on device',
			'Monorepo spanning API, PWA, mobile and desktop clients',
			'Owns its own auth, billing, curriculum and offline sync stack',
		],
		stack: ['Python', 'TypeScript', 'PostgreSQL', 'SQLite', 'PWA', 'Speech AI'],
		image: null,
		demoUrl: null,
		sourceUrl: null,
		status: 'completed',
	},
	{
		id: 3,
		title: 'Nostra Tova Platform',
		tagline: 'Multi-product AI agent monorepo',
		category: 'AI & Agents',
		access: ACCESS.PROPRIETARY,
		year: '2026',
		role: 'Architect & Lead Engineer',
		metric: '1,002 commits',
		summary:
			'The private production monorepo behind the Tova agent family — sixteen shipping packages covering the agent runtime, first-party SDKs, voice, translation, benchmarking and desktop clients.',
		highlights: [
			'First-party Python and TypeScript SDKs generated from one contract',
			'VocaBusta / Vocabanga African-language speech services',
			'MirrorMind and Specio desktop applications',
			'Admin console, analytics dashboard and an agent benchmark harness',
		],
		stack: ['Python', 'TypeScript', 'LangGraph', 'Docker', 'Electron', 'Voice AI'],
		image: null,
		demoUrl: null,
		sourceUrl: null,
		status: 'completed',
	},
	{
		id: 4,
		title: 'NEIP',
		tagline: 'National Education Intelligence Platform',
		category: 'AI & Agents',
		access: ACCESS.PROPRIETARY,
		year: '2026',
		role: 'Lead Engineer',
		summary:
			'A government-facing platform that turns school-level records into national education intelligence for Nigerian ministries and agencies — federal, state, LGA and school views, with a closed intervention loop.',
		highlights: [
			'Data-governance architecture designed to survive a DPO review',
			'Closed intervention loop from detection through to measured outcome',
			'Vendored shared runtime — auth, 2FA, agent shell — re-synced as a directory copy',
			'Prerendered, indexable public government page with an auth-gated console',
		],
		stack: ['React', 'TypeScript', 'Vite', 'Data Governance', 'RBAC'],
		image: null,
		demoUrl: null,
		sourceUrl: null,
		status: 'completed',
	},
	{
		id: 5,
		title: 'ClawPod',
		tagline: 'Multi-cloud GPU orchestration',
		category: 'AI & Agents',
		access: ACCESS.PROPRIETARY,
		year: '2026',
		role: 'Engineer',
		summary:
			'A GPU pod scheduler and autoscaler that provisions inference capacity across RunPod and AWS behind one API, so model workloads scale without hand-managed infrastructure.',
		highlights: [
			'Provider-agnostic scaler with pluggable RunPod and AWS backends',
			'FastAPI control plane with Redis-backed state and scheduled reconciliation',
			'Typer CLI for operators, containerised end to end',
		],
		stack: ['Python', 'FastAPI', 'Redis', 'RunPod', 'AWS', 'Docker'],
		image: null,
		demoUrl: null,
		sourceUrl: null,
		status: 'completed',
	},
	{
		id: 6,
		title: 'Agents Orchestration',
		tagline: 'Multi-agent workflow console',
		category: 'AI & Agents',
		access: ACCESS.PROPRIETARY,
		year: '2026',
		role: 'Engineer',
		summary:
			'A control surface for composing and supervising multi-agent workflows — routing work between specialised agents and keeping a human in the loop over the result.',
		stack: ['React', 'TypeScript', 'Vite', 'Agent Orchestration'],
		image: null,
		demoUrl: null,
		sourceUrl: null,
		status: 'completed',
	},

	/* ──────────────────────────── Health Tech ─────────────────────────────── */
	{
		id: 7,
		title: 'NostraHealth',
		tagline: 'AI medical platform',
		category: 'Health Tech',
		access: ACCESS.PROPRIETARY,
		year: '2024 — present',
		role: 'Machine Learning & Software Engineer',
		summary:
			'The flagship NostraHealth product — an AI-assisted medical platform serving patients, clinicians and partner organisations. I lead the engineering team behind it.',
		highlights: [
			'Live in production at nostrahealth.com',
			'Web, mobile and organisation-facing clients on one platform',
		],
		stack: ['React', 'TypeScript', 'Node.js', 'AI/LLM'],
		image: project1,
		demoUrl: 'https://www.nostrahealth.com/',
		sourceUrl: null,
		status: 'completed',
	},
	{
		id: 8,
		title: 'NostraHealth API',
		tagline: 'FHIR R4 clinical backend',
		category: 'Health Tech',
		access: ACCESS.PROPRIETARY,
		year: '2026',
		role: 'Architect & Lead Engineer',
		metric: '1,228 commits',
		summary:
			'The clinical backend powering every NostraHealth surface — FHIR R4 data layer, multi-provider AI routing, real-time consultation, billing and drug verification.',
		highlights: [
			'FHIR R4 compliant clinical data model with Google Healthcare API integration',
			'Multi-provider AI routing across Anthropic, OpenAI, Gemini and xAI',
			'Live audio/video consultation via Agora, with audio conversation transcription',
			'Subscription billing, doctor–patient access control and barcode drug verification',
		],
		stack: ['Node.js', 'TypeScript', 'FHIR R4', 'Anthropic', 'OpenAI', 'Agora'],
		image: null,
		demoUrl: null,
		sourceUrl: null,
		status: 'completed',
	},
	{
		id: 9,
		title: 'NostraHealth HMS',
		tagline: 'Hospital Management System',
		category: 'Health Tech',
		access: ACCESS.PROPRIETARY,
		year: '2026',
		role: 'Lead Engineer',
		summary:
			'A full hospital management system covering the clinical and administrative surface of a working hospital, on the same FHIR backend as the wider platform.',
		highlights: [
			'Admissions (ADT), bed management and census',
			'Computerised Physician Order Entry, SOAP clinical notes and ED triage',
			'Pharmacy, operating room scheduling and radiology orders',
			'Nigerian HMO integration, quality & compliance reporting, patient portal',
		],
		stack: ['React', 'TypeScript', 'Vite', 'FHIR R4', 'Healthcare Ops'],
		image: null,
		demoUrl: null,
		sourceUrl: null,
		status: 'completed',
	},
	{
		id: 10,
		title: 'NostraHealth for Organisations',
		tagline: 'B2B developer & org console',
		category: 'Health Tech',
		access: ACCESS.PROPRIETARY,
		year: '2026',
		role: 'Lead Engineer',
		summary:
			'The B2B console where partner hospitals and developers manage API access, usage and teams — a glassmorphic dashboard over the NostraHealth API.',
		highlights: [
			'API key lifecycle — issue, revoke, track usage per key',
			'Usage analytics, audit logs and role-based team management',
			'Hospital tier unlocks FHIR records, departments and staff management',
			'JWT auth over HTTP-only cookies',
		],
		stack: ['React', 'TypeScript', 'Zustand', 'React Query', 'Tailwind', 'Recharts'],
		image: null,
		demoUrl: null,
		sourceUrl: null,
		status: 'completed',
	},
	{
		id: 11,
		title: 'Nostra Mobile',
		tagline: 'Cross-platform patient app',
		category: 'Health Tech',
		access: ACCESS.PROPRIETARY,
		year: '2025',
		role: 'Lead Engineer',
		metric: '318 commits',
		summary:
			'The Flutter patient application for NostraHealth, shipping the consultation, ordering and records experience to iOS and Android from one codebase.',
		stack: ['Flutter', 'Dart', 'REST', 'Firebase'],
		image: null,
		demoUrl: null,
		sourceUrl: null,
		status: 'completed',
	},
	{
		id: 12,
		title: 'Satryx AI Mobile',
		tagline: 'Native Flutter agent client',
		category: 'Health Tech',
		access: ACCESS.PROPRIETARY,
		year: '2026',
		role: 'Engineer',
		summary:
			'Native Flutter client for Satryx AI on the Nostra Tova API — agent chat, lessons, business workspaces and store billing in one app.',
		highlights: [
			'In-app purchase entitlements across App Store and Play',
			'Firebase Messaging push with server-side token registration',
			'Boots safely without native config and reports its own setup state',
		],
		stack: ['Flutter', 'Dart', 'Firebase', 'In-App Purchase'],
		image: null,
		demoUrl: null,
		sourceUrl: null,
		status: 'completed',
	},

	/* ─────────────────────────── Open Source ──────────────────────────────── */
	{
		id: 13,
		title: 'Tova',
		tagline: 'Open-source AI agent framework',
		category: 'Open Source',
		access: ACCESS.OPEN_SOURCE,
		year: '2026',
		role: 'Creator',
		summary:
			'An open-source AI agent framework for healthcare order automation, built on LangGraph and deliberately provider-agnostic — bring your own backend, database and LLM.',
		highlights: [
			'Provider pattern: implement a few interfaces to wire the agent to any stack',
			'Medication, device and lab-test ordering; appointments; recurring prescriptions',
			'Works with any LLM provider rather than locking to one vendor',
		],
		stack: ['Python', 'LangGraph', 'LLM Agents', 'Open Source'],
		image: null,
		demoUrl: null,
		sourceUrl: 'https://github.com/Charlex123/tova',
		status: 'completed',
	},
	{
		id: 14,
		title: 'TovaClaw',
		tagline: 'Modular open agent platform',
		category: 'Open Source',
		access: ACCESS.OPEN_SOURCE,
		year: '2026',
		role: 'Creator',
		summary:
			'A modular open-source agent platform where every capability is a module you enable — zero overhead for anything you leave switched off.',
		highlights: [
			'Domains: healthcare, travel, email, productivity and enterprise ops',
			'Custom AI training — upload JSON, CSV, PDF or TXT and query it via RAG',
			'Enterprise modules for CCTV monitoring, fleet tracking and emergency management',
		],
		stack: ['Python', 'LangGraph', 'RAG', 'Open Source'],
		image: null,
		demoUrl: 'https://tovaclaw.vercel.app',
		sourceUrl: 'https://github.com/Charlex123/tovaclaw',
		status: 'completed',
	},
	{
		id: 15,
		title: 'nosi',
		tagline: 'Real-time AI avatar toolkit',
		category: 'Open Source',
		access: ACCESS.OPEN_SOURCE,
		year: '2026',
		role: 'Creator',
		metric: '165 commits in core',
		summary:
			'An open-source toolkit that turns a single face image plus audio into a talking video with realistic lip sync, head motion and eye blinks.',
		highlights: [
			'LivePortrait for appearance capture, head motion and expression',
			'MuseTalk for audio-driven lip sync via single-step latent inpainting',
			'Optional EchoMimicV3 full-body animation and BiRefNet background removal',
			'GPU-accelerated FastAPI serving layer, deployable to RunPod',
		],
		stack: ['Python', 'PyTorch', 'CUDA', 'FastAPI', 'Computer Vision'],
		image: null,
		demoUrl: null,
		sourceUrl: 'https://github.com/Charlex123/nosi',
		status: 'completed',
	},
	{
		id: 16,
		title: 'NostraHealthAI SDKs',
		tagline: 'Official SDKs in four languages',
		category: 'Open Source',
		access: ACCESS.OPEN_SOURCE,
		year: '2026',
		role: 'Author & Maintainer',
		summary:
			'The official client libraries for the NostraHealthAI medical platform, published and maintained across four language ecosystems from a single API contract.',
		highlights: [
			'Python, TypeScript/Node, Java and PHP — one contract, four idiomatic surfaces',
			'Backed by test applications exercising each SDK against the live API',
		],
		stack: ['Python', 'TypeScript', 'Java', 'PHP', 'SDK Design'],
		image: null,
		demoUrl: null,
		sourceUrl: 'https://github.com/Charlex123?tab=repositories&q=nostrahealthai',
		status: 'completed',
	},

	/* ───────────────────── Blockchain & Web3 ──────────────────────────────── */
	{
		id: 17,
		title: 'DogeBrics',
		tagline: 'Solana meme-coin ecosystem',
		category: 'Blockchain',
		access: ACCESS.PROPRIETARY,
		year: '2025',
		role: 'Lead Engineer',
		summary:
			'A full Solana token ecosystem — on-chain programs, the web application and a Telegram bot economy around them.',
		highlights: [
			'Anchor programs in Rust deployed to Solana',
			'Next.js dApp with wallet integration',
			'Companion Telegram bot and Python backend',
		],
		stack: ['Solana', 'Anchor', 'Rust', 'Next.js', 'TypeScript', 'Python'],
		image: project2,
		demoUrl: 'https://dogebricsnext.vercel.app/',
		sourceUrl: null,
		status: 'completed',
	},
	{
		id: 18,
		title: 'FifaReward',
		tagline: 'Web3 rewards platform & tap game',
		category: 'Blockchain',
		access: ACCESS.OPEN_SOURCE,
		year: '2021 — 2024',
		role: 'Software Engineer',
		summary:
			'A blockchain rewards platform I built end to end — smart contracts, web application, AWS infrastructure and a Telegram tap-to-earn game.',
		highlights: [
			'Wrote and deployed the reward smart contracts',
			'Built and shipped the web application front to back',
			'Provisioned AWS infrastructure and the GitHub Actions CI/CD pipeline',
			'Built the Telegram tap game on the Bot API in Python',
		],
		stack: ['Solidity', 'TypeScript', 'Python', 'AWS', 'CI/CD', 'Telegram Bot API'],
		image: project6,
		demoUrl: 'https://fifarewardfrontend.vercel.app',
		sourceUrl: 'https://github.com/Charlex123/fifarewardfrontend',
		status: 'completed',
	},
	{
		id: 19,
		title: 'TafaXtra',
		tagline: 'Crypto community platform',
		category: 'Blockchain',
		access: ACCESS.OPEN_SOURCE,
		year: '2023',
		role: 'Full-Stack Developer',
		summary:
			'A blockchain community and token platform with its own front end and API, shipped end to end.',
		stack: ['JavaScript', 'React', 'Node.js', 'Web3'],
		image: project5,
		demoUrl: 'https://tafafrontend.vercel.app/',
		sourceUrl: 'https://github.com/Charlex123/tafafrontend',
		status: 'completed',
	},

	/* ────────────────────────── Web & Product ─────────────────────────────── */
	{
		id: 20,
		title: 'Outreach Mail Sender',
		tagline: 'Chrome extension + API',
		category: 'Web & Product',
		access: ACCESS.OPEN_SOURCE,
		year: '2024',
		role: 'Full-Stack Developer',
		summary:
			'A Chrome extension that runs outreach mail campaigns from the browser, backed by its own scheduling and delivery API.',
		stack: ['JavaScript', 'React', 'Chrome Extension', 'Node.js'],
		image: project3,
		demoUrl: 'https://outreach-frontend.vercel.app/',
		sourceUrl: 'https://github.com/Charlex123/outreach-frontend',
		status: 'completed',
	},
	{
		id: 21,
		title: 'Perfect Wetsuit',
		tagline: 'Brand commerce site',
		category: 'Web & Product',
		access: ACCESS.PROPRIETARY,
		year: '2023',
		role: 'Full-Stack Developer',
		summary:
			'A Next.js storefront and brand site delivered for a wetsuit company, from design implementation through to deployment.',
		stack: ['Next.js', 'React', 'JavaScript'],
		image: project4,
		demoUrl: 'https://perfectwetsuitv2.vercel.app/',
		sourceUrl: null,
		status: 'completed',
	},
	{
		id: 22,
		title: 'XSO Apartments',
		tagline: 'Property listing platform',
		category: 'Web & Product',
		access: ACCESS.OPEN_SOURCE,
		year: '2025',
		role: 'Full-Stack Developer',
		summary:
			'A property listing and booking front end for short-let apartments, built on React and TypeScript.',
		stack: ['React', 'TypeScript', 'Vite'],
		image: null,
		demoUrl: 'https://xsoapartments.vercel.app',
		sourceUrl: 'https://github.com/Charlex123/xsoapartments',
		status: 'completed',
	},
];

export const projectsNav = [
	{ name: 'all', label: 'All Work' },
	{ name: 'AI & Agents', label: 'AI & Agents' },
	{ name: 'Health Tech', label: 'Health Tech' },
	{ name: 'Open Source', label: 'Open Source' },
	{ name: 'Blockchain', label: 'Blockchain' },
	{ name: 'Web & Product', label: 'Web & Product' },
];
